### ISSUE TITLE
Add combined configurations for v2.6 release

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-dev#11]
Related to https://github.com/mathjax/MathJax/issues/1051

**Comment by pkra** [comment]
## Current

TeX-MML-AM_HTMLorMML 
TeX-AMS-MML_HTMLorMML
TeX-AMS_HTML
MML_HTMLorMML
AM_HTMLorMML
TeX-AMS-MML_SVG
Accessible

## New 

TeX-AMS_HTML5
MML_HTML5
AM_HTML5
TeX-MML-AM_HTML5
TeX-AMS-MML_HTML5

Maybe even add 
TeX-AMS_SVG
MML_SVG
AM_SVG

## Open questions

* Naming convention. CHTML or HTML5?
* Add and activate AssitiveMML.js in all combined configuration files?

I'm in favor of both HTML5 and adding AssistiveMML.js to existing (because our full solution will come out later and for combined configs will mostly affect v3.0 where a) things will be very different and b) we can change our minds. Right now AssitiveMML is the best we can do so let's do it.

**Comment by pkra** [comment]
Oh, I should add I don't care much either way on those. Naming ~1/10, AssitiveMML as default ~4/10.

**Comment by dpvc** [comment]
About naming:  I don't like HTML5, since there is nothing particularly HTML5 about them (especially if we remove the custom tags and go with spans).  The only HTML5 feature is the transforms used for the stretchy characters.  Everything else is HTML4 (which is why IE8 can still do pretty much all of it).  So it seems misleading to use HTML5 to me.

I'm OK with adding the assistive mathml extension.  It hasn't been merged yet,  Are we ready to do that?

**Comment by dpvc** [comment]
The other questions is for the CHTML versions, will we want the fast preview as well?  That will slow down the results (both because the fast preview must be created, and because of the changes in the chunking for the second pass.

**Comment by pkra** [comment]
> I don't like HTML5, 

:ok:

> I'm OK with adding the assistive mathml extension. It hasn't been merged yet, Are we ready to do that?

I think so. Though I expect more feedback during the beta.

> CHTML versions, will we want the fast preview as well

I don't think so. But I'm fine either way. Maybe feedback from the beta should tell us more (e.g., if SE tests CHTML)?

**Comment by pkra** [comment]
Just to repeat from F2F:

Add.

TeX-AMS_CHTML
MML_CHTML
AM_CHTML
TeX-MML-AM_CHTML

TeX-MML-AM_SVG
TeX-AMS_SVG
MML_SVG
AM_SVG

and -full variants of course (and add AssistiveMML to all)

**Comment by pkra** [comment]
As I'm writing the docs, I'm wondering if we shouldn't rename two of the new files

*  TeX-AMS_SVG => TeX_SVG
*  TeX-AMS_CHTML => TeX_SVG

What do you think?

**Comment by dpvc** [comment]
This is inconsistent with the rest of the TeX configurations.  The AMS indicates that the AMSmath and AMSsymbols packages are loaded.  All the other TeX configurations that only load one input jax are named the other way.  Unless you want to rename them all (and make aliases to the old ones so no one's pages break), I'd leave it as is.

**Comment by pkra** [comment]
> This is inconsistent with the rest of the TeX configurations. 

We're already inconsistent, no? We have `TeX-MML-AM_HTMLorMML` which loads the AMS extensions as well -- that's 1 out of 4 combined configs which include TeX input ;-). 

Then we have the inconsistency of `TeX-AMS_HTML` vs `MML_HTMLorMML`

> Unless you want to rename them all

Perhaps that's what I'm actually after.

For the record, HTML_or_MML for the new files also seems odd to me now, as we're deprecating HTMLorMML).

> and make aliases to the old ones

of course.

Sorry for bringing this up on the last minute. I'll think some more as I write along.

**Comment by pkra** [comment]
I'll also accept any veto. Not a huge item for me, just nagging when writing it up.

**Comment by dpvc** [comment]
>  We have TeX-MML-AM_HTMLorMML 

I said that all the ones that *load one input jax* have the AMS listed.  The ones with all three were getting too long, and we left it out, especially with the similarity of AMS and AM.

> Then we have the inconsistency of `TeX-AMS_HTML` vs `MML_HTMLorMML`

This is not inconsistent.  The `TeX-AMS_HTML` file does *not* load the `MMLorHTML` configuration, so it *always* uses the HTML-CSS output.  This was for people who wanted to force the HTML-CSS output rather than trigger the Firefox native MathML output (which was the default in MMLorHTML originally).  So these have different functions, hence different names.

> For the record, `HTMLorMML` for the new files also seems odd to me now, as we're deprecating `MMLorHTML`

What would you like them to be?  Just HTML?  If you rename everything, are you planning to remove the HTMLorMML configurations from the old ones?

**Comment by pkra** [comment]
Oh, let's just forget about this for the beta launch.
