### ISSUE TITLE
improve build tools 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-dev#12]
- evaluate switching to JS tools (grunt, gulp, broccoli etc)
  - would mean moving some parts into core MathJax.
- switch to uglify or other js-based compressors
  - YUI switched itself http://yuiblog.com/blog/2012/10/16/state-of-yui-compressor/
  - closure might be an option
  - or something ES6 based (if ES6 enters the picture)
- simplify building combined configurations
  - enable single-file builds
- optional: set up small service for building combined configurations and dumping them on the CDN.

**Comment by pkra** [comment]
more from the backlog.

* Automate CDN maintenance. Some requirements
  * upload/update releases
    * upload only changed files, control sequence of uploads (e.g., both MathJax.js copies should be last)
  * purge CDN after upload and verify purge
  * verify (and possibly fix) CORS and mimetype headers of webfonts
  * run some basic tests

**Comment by hgl** [comment]
Any progress on this? Would love a more tightly compressed single-file build.

**Comment by dpvc** [comment]
As you may know, we are in the process of a major reorganization of the design for version 3.0, which is a complete rewrite from the ground up.  It is being developed in Typescript, which can be down compiled to ES5 or ES6, and combined files can be created using webpack or similar tools.  You can see the progress so far at the [version 3 repo](https://github.com/mathjax/MathJax-v3).

Because of this change in paradigm, we have not put additional effort into chainging the version 2 packaging at this time.

**Comment by hgl** [comment]
I was not aware of v3. Super excited to know it's in development. Really looking forward to it.

**Comment by dpvc** [comment]
Thanks, we are too!
